### ISSUE TITLE
Fixes on the UI

### ISSUE THREAD

**Issue by Shruti3004** [AgrI-Mitra/app#17]
## Milestones
- [ ] on `/` it should has the same functionality as the `/chat` route.
- [ ] Should add the support to Aadhar Number and Beneficiary ID
     - [ ] Aadhar Number (Numeric / Should be 12 digits)
     - [ ] Benficary Digits (AlphaNumberic / Should be greater than 5)
 - [ ] For the send OTP we have to send the respective uer input (whether it is Aadhar/ Beneficiary ID or Phone Number)
     - [ ] In case of Aadhar and Beneficiary should be logged in with `1234` otp.
 - [ ] Documentation of the components and the API

**Comment by Shruti3004** [comment]
Hey @ChakshuGautam please add, in case and @Amruth-Vamshi and I missed anything.
